// <auto-generated />
namespace ContosoUniversityVersion2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class NoMaxLengthOnNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NoMaxLengthOnNames));
        
        string IMigrationMetadata.Id
        {
            get { return "202102141753327_NoMaxLengthOnNames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
